/* soapStub.h
   Generated by gSOAP 2.8.22 from ims.h

Copyright(C) 2000-2015, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapStub_H
#define soapStub_H
#include "stdsoap2.h"
#if GSOAP_VERSION != 20822
# error "GSOAP VERSION 20822 MISMATCH IN GENERATED CODE VERSUS LIBRARY CODE: PLEASE REINSTALL PACKAGE"
#endif

#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#ifndef SOAP_TYPE__xop__Include
#define SOAP_TYPE__xop__Include (7)
/* Base64 schema type: */
struct _xop__Include
{
	unsigned char *__ptr;
	int __size;
	char *id;	/* optional element of type xsd:string */
	char *type;	/* optional element of type xsd:string */
	char *options;	/* optional element of type xsd:string */
};
typedef struct _xop__Include _xop__Include;
#endif

#ifndef SOAP_TYPE_xmime5__base64Binary
#define SOAP_TYPE_xmime5__base64Binary (11)
/* Base64 schema type: */
struct xmime5__base64Binary
{
	unsigned char *__ptr;
	int __size;
	char *id;	/* optional element of type xsd:string */
	char *type;	/* optional element of type xsd:string */
	char *options;	/* optional element of type xsd:string */
};
typedef struct xmime5__base64Binary xmime5__base64Binary;
#endif

#ifndef SOAP_TYPE_psdims__file
#define SOAP_TYPE_psdims__file (12)
/* Base64 schema type: */
struct psdims__file
{
	unsigned char *__ptr;
	int __size;
};
typedef struct psdims__file psdims__file;
#endif

#ifndef SOAP_TYPE_psdims__string
#define SOAP_TYPE_psdims__string (13)
/* psdims:string */
struct psdims__string
{
	char *string;	/* optional element of type xsd:string */
};
typedef struct psdims__string psdims__string;
#endif

#ifndef SOAP_TYPE_psdims__notif_friend_info
#define SOAP_TYPE_psdims__notif_friend_info (14)
/* psdims:notif-friend-info */
struct psdims__notif_friend_info
{
	struct psdims__string name;	/* required element of type psdims:string */
	int send_date;	/* required element of type xsd:int */
};
typedef struct psdims__notif_friend_info psdims__notif_friend_info;
#endif

#ifndef SOAP_TYPE_psdims__notif_friend_list
#define SOAP_TYPE_psdims__notif_friend_list (15)
/* psdims:notif-friend-list */
struct psdims__notif_friend_list
{
	int __sizenelems;	/* sequence of elements <user> */
	struct psdims__notif_friend_info *user;	/* optional element of type psdims:notif-friend-info */
};
typedef struct psdims__notif_friend_list psdims__notif_friend_list;
#endif

#ifndef SOAP_TYPE_psdims__notif_chat_info
#define SOAP_TYPE_psdims__notif_chat_info (17)
/* psdims:notif-chat-info */
struct psdims__notif_chat_info
{
	int chat_id;	/* required element of type xsd:int */
	int timestamp;	/* required element of type xsd:int */
};
typedef struct psdims__notif_chat_info psdims__notif_chat_info;
#endif

#ifndef SOAP_TYPE_psdims__notif_chat_list
#define SOAP_TYPE_psdims__notif_chat_list (18)
/* psdims:notif-chat-list */
struct psdims__notif_chat_list
{
	int __sizenelems;	/* sequence of elements <chat> */
	struct psdims__notif_chat_info *chat;	/* optional element of type psdims:notif-chat-info */
};
typedef struct psdims__notif_chat_list psdims__notif_chat_list;
#endif

#ifndef SOAP_TYPE_psdims__notif_member_info
#define SOAP_TYPE_psdims__notif_member_info (20)
/* psdims:notif-member-info */
struct psdims__notif_member_info
{
	struct psdims__string name;	/* required element of type psdims:string */
	int chat_id;	/* required element of type xsd:int */
	int timestamp;	/* required element of type xsd:int */
};
typedef struct psdims__notif_member_info psdims__notif_member_info;
#endif

#ifndef SOAP_TYPE_psdims__notif_chat_member_list
#define SOAP_TYPE_psdims__notif_chat_member_list (21)
/* psdims:notif-chat-member-list */
struct psdims__notif_chat_member_list
{
	int __sizenelems;	/* sequence of elements <member> */
	struct psdims__notif_member_info *member;	/* optional element of type psdims:notif-member-info */
};
typedef struct psdims__notif_chat_member_list psdims__notif_chat_member_list;
#endif

#ifndef SOAP_TYPE_psdims__sync
#define SOAP_TYPE_psdims__sync (23)
/* psdims:sync */
struct psdims__sync
{
	struct psdims__notif_chat_list chat_read_timestamps;	/* required element of type psdims:notif-chat-list */
};
typedef struct psdims__sync psdims__sync;
#endif

#ifndef SOAP_TYPE_psdims__new_chat
#define SOAP_TYPE_psdims__new_chat (24)
/* psdims:new-chat */
struct psdims__new_chat
{
	char *description;	/* optional element of type xsd:string */
	char *member;	/* optional element of type xsd:string */
};
typedef struct psdims__new_chat psdims__new_chat;
#endif

#ifndef SOAP_TYPE_psdims__login_info
#define SOAP_TYPE_psdims__login_info (25)
/* psdims:login-info */
struct psdims__login_info
{
	char *name;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
};
typedef struct psdims__login_info psdims__login_info;
#endif

#ifndef SOAP_TYPE_psdims__register_info
#define SOAP_TYPE_psdims__register_info (26)
/* psdims:register-info */
struct psdims__register_info
{
	char *name;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
	char *information;	/* optional element of type xsd:string */
};
typedef struct psdims__register_info psdims__register_info;
#endif

#ifndef SOAP_TYPE_psdims__user_info
#define SOAP_TYPE_psdims__user_info (27)
/* psdims:user-info */
struct psdims__user_info
{
	char *name;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
	char *information;	/* optional element of type xsd:string */
};
typedef struct psdims__user_info psdims__user_info;
#endif

#ifndef SOAP_TYPE_psdims__user_list
#define SOAP_TYPE_psdims__user_list (28)
/* psdims:user-list */
struct psdims__user_list
{
	int __sizenelems;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* sequence of elements <user> */
	struct psdims__user_info *user;	/* optional element of type psdims:user-info */
	int last_timestamp;	/* required element of type xsd:int */
};
typedef struct psdims__user_list psdims__user_list;
#endif

#ifndef SOAP_TYPE_psdims__message_info
#define SOAP_TYPE_psdims__message_info (30)
/* psdims:message-info */
struct psdims__message_info
{
	char *user;	/* optional element of type xsd:string */
	char *text;	/* optional element of type xsd:string */
	char *file_name;	/* optional element of type xsd:string */
	int send_date;	/* required element of type xsd:int */
};
typedef struct psdims__message_info psdims__message_info;
#endif

#ifndef SOAP_TYPE_psdims__message_list
#define SOAP_TYPE_psdims__message_list (31)
/* psdims:message-list */
struct psdims__message_list
{
	int __sizenelems;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* sequence of elements <messages> */
	struct psdims__message_info *messages;	/* optional element of type psdims:message-info */
	int read_timestamp;	/* required element of type xsd:int */
	int last_timestamp;	/* required element of type xsd:int */
};
typedef struct psdims__message_list psdims__message_list;
#endif

#ifndef SOAP_TYPE_psdims__member_list
#define SOAP_TYPE_psdims__member_list (33)
/* psdims:member-list */
struct psdims__member_list
{
	int __sizenelems;	/* sequence of elements <name> */
	struct psdims__string *name;	/* optional element of type psdims:string */
	int last_timestamp;	/* required element of type xsd:int */
};
typedef struct psdims__member_list psdims__member_list;
#endif

#ifndef SOAP_TYPE_psdims__chat_info
#define SOAP_TYPE_psdims__chat_info (35)
/* psdims:chat-info */
struct psdims__chat_info
{
	int chat_id;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
	char *description;	/* optional element of type xsd:string */
	char *admin;	/* optional element of type xsd:string */
	int read_timestamp;	/* required element of type xsd:int */
	int all_read_timestamp;	/* required element of type xsd:int */
	struct psdims__member_list members;	/* required element of type psdims:member-list */
};
typedef struct psdims__chat_info psdims__chat_info;
#endif

#ifndef SOAP_TYPE_psdims__chat_list
#define SOAP_TYPE_psdims__chat_list (36)
/* psdims:chat-list */
struct psdims__chat_list
{
	int __sizenelems;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* sequence of elements <chat-info> */
	struct psdims__chat_info *chat_info;	/* optional element of type psdims:chat-info */
	int last_timestamp;	/* required element of type xsd:int */
};
typedef struct psdims__chat_list psdims__chat_list;
#endif

#ifndef SOAP_TYPE_psdims__notifications
#define SOAP_TYPE_psdims__notifications (38)
/* psdims:notifications */
struct psdims__notifications
{
	struct psdims__notif_friend_list friend_request;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type psdims:notif-friend-list */
	struct psdims__user_list new_friends;	/* required element of type psdims:user-list */
	struct psdims__notif_chat_list chats_with_messages;	/* required element of type psdims:notif-chat-list */
	struct psdims__notif_chat_list chats_read_times;	/* required element of type psdims:notif-chat-list */
	struct psdims__notif_chat_member_list chat_members;	/* required element of type psdims:notif-chat-member-list */
	struct psdims__notif_chat_member_list rem_chat_members;	/* required element of type psdims:notif-chat-member-list */
	struct psdims__notif_chat_member_list chat_admins;	/* required element of type psdims:notif-chat-member-list */
	int last_timestamp;	/* required element of type xsd:int */
};
typedef struct psdims__notifications psdims__notifications;
#endif

#ifndef SOAP_TYPE_psdims__client_data
#define SOAP_TYPE_psdims__client_data (39)
/* psdims:client-data */
struct psdims__client_data
{
	struct psdims__chat_list chats;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type psdims:chat-list */
	struct psdims__user_list friends;	/* required element of type psdims:user-list */
	struct psdims__notif_friend_list friend_requests;	/* required element of type psdims:notif-friend-list */
	int timestamp;	/* required element of type xsd:int */
};
typedef struct psdims__client_data psdims__client_data;
#endif

#ifndef SOAP_TYPE_psdims__user_registerResponse
#define SOAP_TYPE_psdims__user_registerResponse (43)
/* psdims:user-registerResponse */
struct psdims__user_registerResponse
{
	int *ERRCODE;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_psdims__user_register
#define SOAP_TYPE_psdims__user_register (44)
/* psdims:user-register */
struct psdims__user_register
{
	struct psdims__register_info *user_info;	/* optional element of type psdims:register-info */
};
#endif

#ifndef SOAP_TYPE_psdims__user_unregisterResponse
#define SOAP_TYPE_psdims__user_unregisterResponse (47)
/* psdims:user-unregisterResponse */
struct psdims__user_unregisterResponse
{
	int *ERRCODE;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_psdims__user_unregister
#define SOAP_TYPE_psdims__user_unregister (48)
/* psdims:user-unregister */
struct psdims__user_unregister
{
	struct psdims__login_info *login;	/* optional element of type psdims:login-info */
};
#endif

#ifndef SOAP_TYPE_psdims__get_user
#define SOAP_TYPE_psdims__get_user (50)
/* psdims:get-user */
struct psdims__get_user
{
	struct psdims__login_info *login;	/* optional element of type psdims:login-info */
};
#endif

#ifndef SOAP_TYPE_psdims__get_friends
#define SOAP_TYPE_psdims__get_friends (53)
/* psdims:get-friends */
struct psdims__get_friends
{
	struct psdims__login_info *login;	/* optional element of type psdims:login-info */
	int timestamp;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_psdims__get_friend_info
#define SOAP_TYPE_psdims__get_friend_info (55)
/* psdims:get-friend-info */
struct psdims__get_friend_info
{
	struct psdims__login_info *login;	/* optional element of type psdims:login-info */
	char *name;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_psdims__get_chats
#define SOAP_TYPE_psdims__get_chats (58)
/* psdims:get-chats */
struct psdims__get_chats
{
	struct psdims__login_info *login;	/* optional element of type psdims:login-info */
	int timestamp;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_psdims__get_chat_info
#define SOAP_TYPE_psdims__get_chat_info (60)
/* psdims:get-chat-info */
struct psdims__get_chat_info
{
	struct psdims__login_info *login;	/* optional element of type psdims:login-info */
	int chat_id;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_psdims__get_chat_messages
#define SOAP_TYPE_psdims__get_chat_messages (63)
/* psdims:get-chat-messages */
struct psdims__get_chat_messages
{
	struct psdims__login_info *login;	/* optional element of type psdims:login-info */
	int chat_id;	/* required element of type xsd:int */
	int timestamp;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_psdims__get_attachmentResponse
#define SOAP_TYPE_psdims__get_attachmentResponse (66)
/* psdims:get-attachmentResponse */
struct psdims__get_attachmentResponse
{
	struct psdims__file *file;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type psdims:file */
};
#endif

#ifndef SOAP_TYPE_psdims__get_attachment
#define SOAP_TYPE_psdims__get_attachment (67)
/* psdims:get-attachment */
struct psdims__get_attachment
{
	struct psdims__login_info *login;	/* optional element of type psdims:login-info */
	int chat_id;	/* required element of type xsd:int */
	int msg_timestamp;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_psdims__get_pending_notifications
#define SOAP_TYPE_psdims__get_pending_notifications (71)
/* psdims:get-pending-notifications */
struct psdims__get_pending_notifications
{
	struct psdims__login_info *login;	/* optional element of type psdims:login-info */
	int timestamp;	/* required element of type xsd:int */
	struct psdims__sync *sync;	/* optional element of type psdims:sync */
};
#endif

#ifndef SOAP_TYPE_psdims__get_all_data
#define SOAP_TYPE_psdims__get_all_data (74)
/* psdims:get-all-data */
struct psdims__get_all_data
{
	struct psdims__login_info *login;	/* optional element of type psdims:login-info */
};
#endif

#ifndef SOAP_TYPE_psdims__create_chatResponse
#define SOAP_TYPE_psdims__create_chatResponse (77)
/* psdims:create-chatResponse */
struct psdims__create_chatResponse
{
	int *chat_id;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_psdims__create_chat
#define SOAP_TYPE_psdims__create_chat (78)
/* psdims:create-chat */
struct psdims__create_chat
{
	struct psdims__login_info *login;	/* optional element of type psdims:login-info */
	struct psdims__new_chat *new_chat;	/* optional element of type psdims:new-chat */
};
#endif

#ifndef SOAP_TYPE_psdims__add_memberResponse
#define SOAP_TYPE_psdims__add_memberResponse (80)
/* psdims:add-memberResponse */
struct psdims__add_memberResponse
{
	int *ERRCODE;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_psdims__add_member
#define SOAP_TYPE_psdims__add_member (81)
/* psdims:add-member */
struct psdims__add_member
{
	struct psdims__login_info *login;	/* optional element of type psdims:login-info */
	char *name;	/* optional element of type xsd:string */
	int chat_id;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_psdims__remove_memberResponse
#define SOAP_TYPE_psdims__remove_memberResponse (83)
/* psdims:remove-memberResponse */
struct psdims__remove_memberResponse
{
	int *ERRCODE;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_psdims__remove_member
#define SOAP_TYPE_psdims__remove_member (84)
/* psdims:remove-member */
struct psdims__remove_member
{
	struct psdims__login_info *login;	/* optional element of type psdims:login-info */
	char *name;	/* optional element of type xsd:string */
	int chat_id;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_psdims__quit_from_chatResponse
#define SOAP_TYPE_psdims__quit_from_chatResponse (86)
/* psdims:quit-from-chatResponse */
struct psdims__quit_from_chatResponse
{
	int *ERRCODE;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_psdims__quit_from_chat
#define SOAP_TYPE_psdims__quit_from_chat (87)
/* psdims:quit-from-chat */
struct psdims__quit_from_chat
{
	struct psdims__login_info *login;	/* optional element of type psdims:login-info */
	int chat_id;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_psdims__send_messageResponse
#define SOAP_TYPE_psdims__send_messageResponse (89)
/* psdims:send-messageResponse */
struct psdims__send_messageResponse
{
	int *timestamp;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_psdims__send_message
#define SOAP_TYPE_psdims__send_message (90)
/* psdims:send-message */
struct psdims__send_message
{
	struct psdims__login_info *login;	/* optional element of type psdims:login-info */
	int chat_id;	/* required element of type xsd:int */
	struct psdims__message_info *message;	/* optional element of type psdims:message-info */
};
#endif

#ifndef SOAP_TYPE_psdims__send_attachmentResponse
#define SOAP_TYPE_psdims__send_attachmentResponse (92)
/* psdims:send-attachmentResponse */
struct psdims__send_attachmentResponse
{
	int *ERRCODE;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_psdims__send_attachment
#define SOAP_TYPE_psdims__send_attachment (93)
/* psdims:send-attachment */
struct psdims__send_attachment
{
	struct psdims__login_info *login;	/* optional element of type psdims:login-info */
	int chat_id;	/* required element of type xsd:int */
	int msg_timestamp;	/* required element of type xsd:int */
	struct psdims__file *file;	/* optional element of type psdims:file */
};
#endif

#ifndef SOAP_TYPE_psdims__send_friend_requestResponse
#define SOAP_TYPE_psdims__send_friend_requestResponse (95)
/* psdims:send-friend-requestResponse */
struct psdims__send_friend_requestResponse
{
	int *timestamp;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_psdims__send_friend_request
#define SOAP_TYPE_psdims__send_friend_request (96)
/* psdims:send-friend-request */
struct psdims__send_friend_request
{
	struct psdims__login_info *login;	/* optional element of type psdims:login-info */
	char *request_name;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_psdims__accept_requestResponse
#define SOAP_TYPE_psdims__accept_requestResponse (98)
/* psdims:accept-requestResponse */
struct psdims__accept_requestResponse
{
	int *timestamp;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_psdims__accept_request
#define SOAP_TYPE_psdims__accept_request (99)
/* psdims:accept-request */
struct psdims__accept_request
{
	struct psdims__login_info *login;	/* optional element of type psdims:login-info */
	char *request_name;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_psdims__decline_requestResponse
#define SOAP_TYPE_psdims__decline_requestResponse (101)
/* psdims:decline-requestResponse */
struct psdims__decline_requestResponse
{
	int *timestamp;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_psdims__decline_request
#define SOAP_TYPE_psdims__decline_request (102)
/* psdims:decline-request */
struct psdims__decline_request
{
	struct psdims__login_info *login;	/* optional element of type psdims:login-info */
	char *request_name;	/* optional element of type xsd:string */
};
#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (103)
/* SOAP Header: */
struct SOAP_ENV__Header
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* empty struct is a GNU extension */
#endif
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (104)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (106)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
	char *__any;
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (109)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (110)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Server-Side Operations                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 psdims__user_register(struct soap*, struct psdims__register_info *user_info, int *ERRCODE);

SOAP_FMAC5 int SOAP_FMAC6 psdims__user_unregister(struct soap*, struct psdims__login_info *login, int *ERRCODE);

SOAP_FMAC5 int SOAP_FMAC6 psdims__get_user(struct soap*, struct psdims__login_info *login, struct psdims__user_info *user);

SOAP_FMAC5 int SOAP_FMAC6 psdims__get_friends(struct soap*, struct psdims__login_info *login, int timestamp, struct psdims__user_list *friends);

SOAP_FMAC5 int SOAP_FMAC6 psdims__get_friend_info(struct soap*, struct psdims__login_info *login, char *name, struct psdims__user_info *friend_info);

SOAP_FMAC5 int SOAP_FMAC6 psdims__get_chats(struct soap*, struct psdims__login_info *login, int timestamp, struct psdims__chat_list *chats);

SOAP_FMAC5 int SOAP_FMAC6 psdims__get_chat_info(struct soap*, struct psdims__login_info *login, int chat_id, struct psdims__chat_info *chat);

SOAP_FMAC5 int SOAP_FMAC6 psdims__get_chat_messages(struct soap*, struct psdims__login_info *login, int chat_id, int timestamp, struct psdims__message_list *messages);

SOAP_FMAC5 int SOAP_FMAC6 psdims__get_attachment(struct soap*, struct psdims__login_info *login, int chat_id, int msg_timestamp, struct psdims__file *file);

SOAP_FMAC5 int SOAP_FMAC6 psdims__get_pending_notifications(struct soap*, struct psdims__login_info *login, int timestamp, struct psdims__sync *sync, struct psdims__notifications *notifications);

SOAP_FMAC5 int SOAP_FMAC6 psdims__get_all_data(struct soap*, struct psdims__login_info *login, struct psdims__client_data *client_data);

SOAP_FMAC5 int SOAP_FMAC6 psdims__create_chat(struct soap*, struct psdims__login_info *login, struct psdims__new_chat *new_chat, int *chat_id);

SOAP_FMAC5 int SOAP_FMAC6 psdims__add_member(struct soap*, struct psdims__login_info *login, char *name, int chat_id, int *ERRCODE);

SOAP_FMAC5 int SOAP_FMAC6 psdims__remove_member(struct soap*, struct psdims__login_info *login, char *name, int chat_id, int *ERRCODE);

SOAP_FMAC5 int SOAP_FMAC6 psdims__quit_from_chat(struct soap*, struct psdims__login_info *login, int chat_id, int *ERRCODE);

SOAP_FMAC5 int SOAP_FMAC6 psdims__send_message(struct soap*, struct psdims__login_info *login, int chat_id, struct psdims__message_info *message, int *timestamp);

SOAP_FMAC5 int SOAP_FMAC6 psdims__send_attachment(struct soap*, struct psdims__login_info *login, int chat_id, int msg_timestamp, struct psdims__file *file, int *ERRCODE);

SOAP_FMAC5 int SOAP_FMAC6 psdims__send_friend_request(struct soap*, struct psdims__login_info *login, char *request_name, int *timestamp);

SOAP_FMAC5 int SOAP_FMAC6 psdims__accept_request(struct soap*, struct psdims__login_info *login, char *request_name, int *timestamp);

SOAP_FMAC5 int SOAP_FMAC6 psdims__decline_request(struct soap*, struct psdims__login_info *login, char *request_name, int *timestamp);

/******************************************************************************\
 *                                                                            *
 * Server-Side Skeletons to Invoke Service Operations                         *
 *                                                                            *
\******************************************************************************/

SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_psdims__user_register(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_psdims__user_unregister(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_psdims__get_user(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_psdims__get_friends(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_psdims__get_friend_info(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_psdims__get_chats(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_psdims__get_chat_info(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_psdims__get_chat_messages(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_psdims__get_attachment(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_psdims__get_pending_notifications(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_psdims__get_all_data(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_psdims__create_chat(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_psdims__add_member(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_psdims__remove_member(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_psdims__quit_from_chat(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_psdims__send_message(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_psdims__send_attachment(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_psdims__send_friend_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_psdims__accept_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_psdims__decline_request(struct soap*);

/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stubs                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call_psdims__user_register(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct psdims__register_info *user_info, int *ERRCODE);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_psdims__user_unregister(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct psdims__login_info *login, int *ERRCODE);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_psdims__get_user(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct psdims__login_info *login, struct psdims__user_info *user);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_psdims__get_friends(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct psdims__login_info *login, int timestamp, struct psdims__user_list *friends);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_psdims__get_friend_info(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct psdims__login_info *login, char *name, struct psdims__user_info *friend_info);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_psdims__get_chats(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct psdims__login_info *login, int timestamp, struct psdims__chat_list *chats);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_psdims__get_chat_info(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct psdims__login_info *login, int chat_id, struct psdims__chat_info *chat);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_psdims__get_chat_messages(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct psdims__login_info *login, int chat_id, int timestamp, struct psdims__message_list *messages);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_psdims__get_attachment(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct psdims__login_info *login, int chat_id, int msg_timestamp, struct psdims__file *file);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_psdims__get_pending_notifications(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct psdims__login_info *login, int timestamp, struct psdims__sync *sync, struct psdims__notifications *notifications);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_psdims__get_all_data(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct psdims__login_info *login, struct psdims__client_data *client_data);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_psdims__create_chat(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct psdims__login_info *login, struct psdims__new_chat *new_chat, int *chat_id);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_psdims__add_member(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct psdims__login_info *login, char *name, int chat_id, int *ERRCODE);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_psdims__remove_member(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct psdims__login_info *login, char *name, int chat_id, int *ERRCODE);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_psdims__quit_from_chat(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct psdims__login_info *login, int chat_id, int *ERRCODE);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_psdims__send_message(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct psdims__login_info *login, int chat_id, struct psdims__message_info *message, int *timestamp);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_psdims__send_attachment(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct psdims__login_info *login, int chat_id, int msg_timestamp, struct psdims__file *file, int *ERRCODE);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_psdims__send_friend_request(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct psdims__login_info *login, char *request_name, int *timestamp);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_psdims__accept_request(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct psdims__login_info *login, char *request_name, int *timestamp);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_psdims__decline_request(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct psdims__login_info *login, char *request_name, int *timestamp);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapStub.h */
